---
all:
  hosts:
    mailer:
      # change to fit the setting in start-mailer.yml
      ansible_host: example.northcentralus.cloudapp.azure.com
      ansible_port: 22
      ansible_user: azureadmin
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_azure
      ansible_become: yes
    localhost:
      ansible_python_interpreter: /home/benjamin/.virtualenvs/mail-demo/bin/python
...
